### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by ankush981** [gilsondev/pelican-clean-blog#41]
Hi, there! I'm new to Pelican and really love this theme. But I have no idea how to install and use it. Any tips?

**Comment by gilsondev** [comment]
http://docs.getpelican.com/en/3.6.3/install.html

**Comment by ankush981** [comment]
Thanks, although I found the link http://docs.getpelican.com/en/latest/themes.html#theming-pelican more helpful. This is a beautiful theme, by the way. Thanks for making it! P.S.: Can I do something to contribute?
