### ISSUE TITLE
Having problems with the new translation feature (gettext)

### ISSUE THREAD

**Issue by dcanones** [gilsondev/pelican-clean-blog#62]
Hi!

I updated recently to the newer version of this theme but I am getting a jijnja2 error which stands that there is a problem with **gettext** (I guess it is related with the new translation feature). I am developing my blog in Ubuntu. Any idea about how to solve it? I switched temporarily to an older version of this theme while I figure out how to make it work.

Thanks!

**Comment by silentjay** [comment]
same here:

```
File "/templates/article.html", line 108, in block "header"
    <span class="meta">{{ gettext('Posted by') }}
jinja2.exceptions.UndefinedError: 'gettext' is undefined
```

**Comment by silentjay** [comment]
Got it working, tried a load of things so not exactly sure what did the trick but think it might of been adding:

```
JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}

PLUGIN_PATHS = ["plugins", "~/Development/blog/plugins"]

PLUGINS = ['i18n_subsites',]
```

**Comment by dcanones** [comment]
I will check your solution asap! Thanks in advance @silentjay. I will report here if it also works for me. @gilsondev should consider add this plugin dependencies to readme if needed.

**Comment by gilsondev** [comment]
Yes, sure.
