### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by jorgesumle** [gilsondev/pelican-clean-blog#65]
> Theme based in [Clean Blog layout](http://ironsummitmedia.github.io/startbootstrap-clean-blog/).

http://ironsummitmedia.github.io/startbootstrap-clean-blog/ (broken link)

**Comment by gilsondev** [comment]
Link: https://github.com/BlackrockDigital/startbootstrap-clean-blog

**Comment by GeekyShacklebolt** [comment]
Hey @gilsondev 
I was looking to contribute to this repository and found this easy issue has been opened for a long time without a recent activity so thought of picking it up. Therefore, I have made the PR to fix the link.

**Comment by gilsondev** [comment]
Thinks @GeekyShacklebolt :)
